// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4LiqvTubabIHDIgn7GbCxGDXDaDazQtw',
    appId: '1:829596159772:web:525601499821b2097c74d9',
    messagingSenderId: '829596159772',
    projectId: 'coffeeflutter-53a99',
    authDomain: 'coffeeflutter-53a99.firebaseapp.com',
    storageBucket: 'coffeeflutter-53a99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRICiF69U-pxIBDsGCC8tR3tCiMFi5e6o',
    appId: '1:829596159772:android:5e8830992c9024987c74d9',
    messagingSenderId: '829596159772',
    projectId: 'coffeeflutter-53a99',
    storageBucket: 'coffeeflutter-53a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarjx2uyvpwNVDwgCM4cRWYYLX2NxjxPY',
    appId: '1:829596159772:ios:901fb88569ff30ec7c74d9',
    messagingSenderId: '829596159772',
    projectId: 'coffeeflutter-53a99',
    storageBucket: 'coffeeflutter-53a99.appspot.com',
    iosClientId: '829596159772-ccv5lc6l108vero8f6mh0loroljbmvdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarjx2uyvpwNVDwgCM4cRWYYLX2NxjxPY',
    appId: '1:829596159772:ios:901fb88569ff30ec7c74d9',
    messagingSenderId: '829596159772',
    projectId: 'coffeeflutter-53a99',
    storageBucket: 'coffeeflutter-53a99.appspot.com',
    iosClientId: '829596159772-ccv5lc6l108vero8f6mh0loroljbmvdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
